### ISSUE TITLE
An error occurred while getting an unique user ID: FetchError

### ISSUE THREAD

**Issue by enzanki-ars** [JustJoostNL/F1MV-Lights-Integration#40] opened 2023-08-25 13:56 UTC
It appears that this app is not connecting to F1MV due to an unrelated failure in the `getUniqueID` call, seemingly an IPv6 error, as this request does work properly in the browser.

With full debug logs on:
```
[2023-08-25 09:46:39.596] [info] There are no updates available.
[2023-08-25 09:46:38.014] [error] An error occurred while getting an unique user ID: FetchError: request to https://api.jstt.me/api/v2/f1mvli/analytics/active-users/getUniqueID failed, reason: connect EACCES 2606:4700:3031::6815:29fb:443
[2023-08-25 09:46:37.885] [info] App starting...
```

**Comment by JustJoostNL** [comment] 2023-08-25 14:10
Hey, thanks for reporting!

It actually doesn't have to do with F1MV but with the analytics of F1MV Lights Integration, so it shouldn't impact the F1MV connection.

I am currently investigating the analytics issue.

**Comment by JustJoostNL** [comment] 2023-08-26 14:46
Hey,

I investigated a bit, and it turns out it's probably an issue with your DNS.

Since I can't reproduce this, I will close this issue.

**Closed by JustJoostNL** 2023-08-26 14:46 UTC

**Comment by enzanki-ars** [comment] 2023-08-27 15:19
Then it appears that I might have a related issue then.  The app does not connect to Multiviewer.  Multiviewer is configured with allow untrusted, firewall is allowed (not that it should matter for localhost), this app is configured in default mode for `http://localhost:10101`, and other apps like Ultimate F1 viewer and my own code interfacing with the API connects fine.  When I look at the both the logs for this app and also Wireshark on all interfaces, including localhost, I don't see any traffic to port 10101.  The DNS could be AT&T being bad at IPv6, and I'll have to investigate that separately, as I thought I solved that before already....

**Comment by JustJoostNL** [comment] 2023-08-27 16:07
Hey, could you try "http://0.0.0.0:10101"?
