### ISSUE TITLE
Config reset every time.

### ISSUE THREAD

**Issue by LapsTimeOFF** [JustJoostNL/F1MV-Lights-Integration#18] opened 2023-02-12 11:13 UTC
**OS:** MacOS Ventura 13.1

**Issues:**
Every time I :
 * Update
 * Go to the Settings Menu then to home
 * Close the Hue select thing<br/>

The whole config is reset....

**Comment by JustJoostNL** [comment] 2023-02-14 18:51
Hey, I am closing the issue due to the following:

I tried to reproduce the issue on my Mac, and everything is working perfectly. I think that means you have some kind of local issue, I don't know exactly what is causing it, but you can try to do the following steps:

1. Create a new user on your Mac
2. Install F1MV-Lights-Integration
3. Check if the issue still persists.

Honestly, if the issue persists, I don't know how to solve it.

But, if this solved the issue, the problem is probably that on your normal user, it has cached something.

On your normal user, you can try deleting some caching files that Electron creates, and try again. (I don't know exactly where those files are).

For any further question, feel free to contact me on Discord!

**Closed by JustJoostNL** 2023-02-14 18:51 UTC
Labels: bug

**Comment by LapsTimeOFF** [comment] 2023-02-14 18:53
Hey! I totally understand. I’ve tried to delete the whole ”F1MV-Lights-Integration” folder in Library but nothing happened. I will try soon with another user.
